### ISSUE TITLE
Fix broken mock reporting

### ISSUE THREAD

**Issue by vigoo** [zio/zio-mock#22] opened 2022-05-13 08:09 UTC
Broke with the upgrade to ZIO 2.0.0-RC6, `MockReporterSpec` suite is now temporarily ignored to unblock migration of other projects.

**Comment by bilal-fazlani** [comment] 2022-09-05 09:17
👀 
Using zio-mock is very difficult without reporting

**Comment by soujiro32167** [comment] 2022-10-04 15:59
May be the cause of https://github.com/zio/zio-mock/issues/35

**Comment by regiskuckaertz** [comment] 2023-11-17 07:57
Fixed in #51

**Closed** 2023-11-17 08:36 UTC
